language: node_js
node_js:
  - 'stable'
  - '5'
  
before_install:
  - npm install -g bower
install: 
- npm install
#- bower install 
#- gulp --cordova "prepare" --force-build
#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - npm start > /dev/null &
#  - npm run update-webdriver
#  - sleep 1 # give server time to start
# script: gulp build
#script:
#  - node_modules/karma/bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox

branches:
  only:
    - master

notifications:
  slack: oklabgi:g8CTO3fWd4m2LMIZ2AQ5uHQo
